name: show the file content

on:
  push:

jobs:
  show:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: List files
        run: ls -lrth

      - name: Print working directory
        run: pwd