name: Execute Shell Script

on:
  workflow_dispatch:

jobs:
  run-script-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Give execute Permission to script
        run: chmod +x .github/workflows/myscript.sh

      - name: Run the shell script
        run: .github/workflows/myscript.sh