name: Env Demo

on: workflow_dispatch

jobs:
  env-demo:
    runs-on: ubuntu-latest

    steps:
      - name: Print predefined env
        run: echo "Repo Name is $GITHUB_REPOSITORY"

      - name: Set and print custom env
        run: |
          MYNAME="RAJKUMAR"
          echo "My name is $MYNAME"