name: KK FUNDA Demo Workflow

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "checkout suucssfully"
      - run: echo "created artifacts"
      - run: echo "artifact pushed suucssfully"

      - run: echo "deployment done."
