name: Artifact Upload and Download Example

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: Create file
        run: echo "Hello We are working on GIthub actions wirh manual triggering" > Myfile.txt

      - name: Upload file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: datafile
          path: Myfile.txt

  job2:
    runs-on: ubuntu-latest
    needs: job1

    steps:
      - name: Download artifact file
        uses: actions/download-artifact@v4
        with:
          name: datafile

      - name: Show file content
        run: cat Myfile.txt

      - name: Show me the files list 
        run: ls -lrth 
        



    
